name = "zx_calculus"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ZxCalculus"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "d9d1cc1012eccfc8d01215b1b7943b0e7f8b7757"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "185d6a66e625502e2760f1a001dd8a0b64b98ac0"

[[require]]
name = "quantumInfo"
git = "https://github.com/Timeroot/Lean-QuantumInfo.git"
rev = "bf347dc9538097f0b7fd4123fa21266198348020"

[[lean_lib]]
name = "ZxCalculus"

[[lean_lib]]
name = "tests"